using BancoHorizonte.Api.Domain;
using Microsoft.EntityFrameworkCore;

namespace BancoHorizonte.Api.Infrastructure;

public sealed class AppDbContext(DbContextOptions<AppDbContext> options) : DbContext(options)
{
    public DbSet<Role> Roles => Set<Role>();
    public DbSet<AppUser> Users => Set<AppUser>();
    public DbSet<UserRole> UserRoles => Set<UserRole>();
    public DbSet<Customer> Customers => Set<Customer>();
    public DbSet<ReceptionChannel> ReceptionChannels => Set<ReceptionChannel>();
    public DbSet<ComplaintCategory> Categories => Set<ComplaintCategory>();
    public DbSet<ComplaintSubcategory> Subcategories => Set<ComplaintSubcategory>();
    public DbSet<ComplaintStatus> Statuses => Set<ComplaintStatus>();
    public DbSet<StatusTransition> StatusTransitions => Set<StatusTransition>();
    public DbSet<PriorityLevel> Priorities => Set<PriorityLevel>();
    public DbSet<SlaPolicy> SlaPolicies => Set<SlaPolicy>();
    public DbSet<Complaint> Complaints => Set<Complaint>();
    public DbSet<ComplaintAssignment> Assignments => Set<ComplaintAssignment>();
    public DbSet<ComplaintObservation> Observations => Set<ComplaintObservation>();
    public DbSet<ComplaintHistory> History => Set<ComplaintHistory>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.HasDefaultSchema("public");
        modelBuilder.Entity<Role>(e => { e.ToTable("roles"); e.Property(x => x.Id).HasColumnName("id"); e.Property(x => x.Name).HasColumnName("nombre"); e.Property(x => x.Description).HasColumnName("descripcion"); e.Property(x => x.IsActive).HasColumnName("activo"); });
        modelBuilder.Entity<AppUser>(e => { e.ToTable("usuarios"); e.Property(x => x.Id).HasColumnName("id"); e.Property(x => x.FirstNames).HasColumnName("nombres"); e.Property(x => x.LastNames).HasColumnName("apellidos"); e.Property(x => x.Email).HasColumnName("correo"); e.Property(x => x.IsActive).HasColumnName("activo"); e.Property(x => x.CreatedAt).HasColumnName("creado_en"); e.Property(x => x.UpdatedAt).HasColumnName("actualizado_en"); });
        modelBuilder.Entity<UserRole>(e => { e.ToTable("usuario_roles"); e.HasKey(x => new { x.UserId, x.RoleId }); e.Property(x => x.UserId).HasColumnName("usuario_id"); e.Property(x => x.RoleId).HasColumnName("rol_id"); e.HasOne(x => x.User).WithMany(x => x.UserRoles).HasForeignKey(x => x.UserId); e.HasOne(x => x.Role).WithMany().HasForeignKey(x => x.RoleId); });
        modelBuilder.Entity<Customer>(e => { e.ToTable("clientes"); e.Property(x => x.Id).HasColumnName("id"); e.Property(x => x.DocumentType).HasColumnName("tipo_documento"); e.Property(x => x.DocumentNumber).HasColumnName("numero_documento"); e.Property(x => x.FirstNames).HasColumnName("nombres"); e.Property(x => x.LastNames).HasColumnName("apellidos"); e.Property(x => x.Email).HasColumnName("correo"); e.Property(x => x.Phone).HasColumnName("telefono"); e.Property(x => x.CreatedAt).HasColumnName("creado_en"); e.Property(x => x.UpdatedAt).HasColumnName("actualizado_en"); });
        modelBuilder.Entity<ReceptionChannel>(e => { e.ToTable("canales_recepcion"); e.Property(x => x.Id).HasColumnName("id"); e.Property(x => x.Name).HasColumnName("nombre"); e.Property(x => x.IsActive).HasColumnName("activo"); });
        modelBuilder.Entity<ComplaintCategory>(e => { e.ToTable("categorias_reclamo"); e.Property(x => x.Id).HasColumnName("id"); e.Property(x => x.Name).HasColumnName("nombre"); e.Property(x => x.Description).HasColumnName("descripcion"); e.Property(x => x.IsActive).HasColumnName("activo"); });
        modelBuilder.Entity<ComplaintSubcategory>(e => { e.ToTable("subcategorias_reclamo"); e.Property(x => x.Id).HasColumnName("id"); e.Property(x => x.CategoryId).HasColumnName("categoria_id"); e.Property(x => x.Name).HasColumnName("nombre"); e.Property(x => x.IsActive).HasColumnName("activo"); });
        modelBuilder.Entity<ComplaintStatus>(e => { e.ToTable("estados_reclamo"); e.Property(x => x.Id).HasColumnName("id"); e.Property(x => x.Name).HasColumnName("nombre"); e.Property(x => x.IsFinal).HasColumnName("es_final"); e.Property(x => x.Order).HasColumnName("orden"); e.Property(x => x.IsActive).HasColumnName("activo"); });
        modelBuilder.Entity<StatusTransition>(e => { e.ToTable("transiciones_estado"); e.HasKey(x => new { x.FromStatusId, x.ToStatusId }); e.Property(x => x.FromStatusId).HasColumnName("estado_origen_id"); e.Property(x => x.ToStatusId).HasColumnName("estado_destino_id"); });
        modelBuilder.Entity<PriorityLevel>(e => { e.ToTable("niveles_prioridad"); e.Property(x => x.Id).HasColumnName("id"); e.Property(x => x.Name).HasColumnName("nombre"); e.Property(x => x.MinimumScore).HasColumnName("puntaje_minimo"); e.Property(x => x.Order).HasColumnName("orden"); e.Property(x => x.ColorHex).HasColumnName("color_hex"); e.Property(x => x.IsActive).HasColumnName("activo"); });
        modelBuilder.Entity<SlaPolicy>(e => { e.ToTable("politicas_sla"); e.Property(x => x.Id).HasColumnName("id"); e.Property(x => x.Name).HasColumnName("nombre"); e.Property(x => x.CategoryId).HasColumnName("categoria_id"); e.Property(x => x.PriorityId).HasColumnName("prioridad_id"); e.Property(x => x.ResolutionHours).HasColumnName("horas_resolucion"); e.Property(x => x.AlertThresholdMinutes).HasColumnName("umbral_alerta_minutos"); e.Property(x => x.ValidFrom).HasColumnName("vigente_desde"); e.Property(x => x.ValidUntil).HasColumnName("vigente_hasta"); e.Property(x => x.IsActive).HasColumnName("activo"); });
        modelBuilder.Entity<Complaint>(e => { e.ToTable("reclamos"); e.Property(x => x.Id).HasColumnName("id"); e.Property(x => x.Code).HasColumnName("codigo"); e.Property(x => x.CustomerId).HasColumnName("cliente_id"); e.Property(x => x.ReceptionChannelId).HasColumnName("canal_recepcion_id"); e.Property(x => x.CategoryId).HasColumnName("categoria_id"); e.Property(x => x.SubcategoryId).HasColumnName("subcategoria_id"); e.Property(x => x.Description).HasColumnName("descripcion"); e.Property(x => x.Impact).HasColumnName("impacto"); e.Property(x => x.Urgency).HasColumnName("urgencia"); e.Property(x => x.StatusId).HasColumnName("estado_id"); e.Property(x => x.PriorityId).HasColumnName("prioridad_id"); e.Property(x => x.PriorityScore).HasColumnName("puntaje_prioridad"); e.Property(x => x.SlaPolicyId).HasColumnName("politica_sla_id"); e.Property(x => x.ReceivedAt).HasColumnName("fecha_recepcion"); e.Property(x => x.SlaDeadline).HasColumnName("fecha_limite_sla"); e.Property(x => x.ResolvedAt).HasColumnName("fecha_resolucion"); e.Property(x => x.CurrentAssigneeId).HasColumnName("responsable_actual_id"); e.Property(x => x.CreatedByUserId).HasColumnName("creado_por_usuario_id"); e.Property(x => x.CreatedAt).HasColumnName("creado_en"); e.Property(x => x.UpdatedAt).HasColumnName("actualizado_en"); e.HasOne(x => x.Customer).WithMany().HasForeignKey(x => x.CustomerId); e.HasOne(x => x.ReceptionChannel).WithMany().HasForeignKey(x => x.ReceptionChannelId); e.HasOne(x => x.Category).WithMany().HasForeignKey(x => x.CategoryId); e.HasOne(x => x.Subcategory).WithMany().HasForeignKey(x => x.SubcategoryId); e.HasOne(x => x.Status).WithMany().HasForeignKey(x => x.StatusId); e.HasOne(x => x.Priority).WithMany().HasForeignKey(x => x.PriorityId); e.HasOne(x => x.SlaPolicy).WithMany().HasForeignKey(x => x.SlaPolicyId); e.HasOne(x => x.CurrentAssignee).WithMany().HasForeignKey(x => x.CurrentAssigneeId); });
        modelBuilder.Entity<ComplaintAssignment>(e => { e.ToTable("asignaciones_reclamo"); e.Property(x => x.Id).HasColumnName("id"); e.Property(x => x.ComplaintId).HasColumnName("reclamo_id"); e.Property(x => x.AnalystId).HasColumnName("analista_id"); e.Property(x => x.AssignedByUserId).HasColumnName("asignado_por_usuario_id"); e.Property(x => x.AssignedAt).HasColumnName("asignado_en"); e.Property(x => x.EndedAt).HasColumnName("finalizado_en"); e.Property(x => x.Reason).HasColumnName("motivo"); });
        modelBuilder.Entity<ComplaintObservation>(e => { e.ToTable("observaciones_reclamo"); e.Property(x => x.Id).HasColumnName("id"); e.Property(x => x.ComplaintId).HasColumnName("reclamo_id"); e.Property(x => x.AuthorUserId).HasColumnName("autor_usuario_id"); e.Property(x => x.Content).HasColumnName("contenido"); e.Property(x => x.IsInternal).HasColumnName("es_interna"); e.Property(x => x.CreatedAt).HasColumnName("creado_en"); e.HasOne(x => x.Author).WithMany().HasForeignKey(x => x.AuthorUserId); });
        modelBuilder.Entity<ComplaintHistory>(e => { e.ToTable("historial_reclamo"); e.Property(x => x.Id).HasColumnName("id"); e.Property(x => x.ComplaintId).HasColumnName("reclamo_id"); e.Property(x => x.ActorUserId).HasColumnName("actor_usuario_id"); e.Property(x => x.EventType).HasColumnName("tipo_evento"); e.Property(x => x.BeforeData).HasColumnName("datos_antes").HasColumnType("jsonb"); e.Property(x => x.AfterData).HasColumnName("datos_despues").HasColumnType("jsonb"); e.Property(x => x.OccurredAt).HasColumnName("ocurrido_en"); e.HasOne(x => x.Actor).WithMany().HasForeignKey(x => x.ActorUserId); });
    }
}
